### ISSUE TITLE
Uninformative error message when trying to upload already existing file

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/dync#1]
When I try to upload a file that already exists on the server side storage, I got the following traceback and error message:

`Traceback (most recent call last):
  File "/usr/bin/dync", line 11, in <module>
    load_entry_point('dync', 'console_scripts', 'dync')()
  File "/home/sven1103/git/dync/dync/client.py", line 234, in main
    server_pk, pk, sk, args.name, filesize, progress)
  File "/home/sven1103/git/dync/dync/client.py", line 213, in send_file
    filesize=filesize, progress=progress).serve()
  File "/home/sven1103/git/dync/dync/client.py", line 134, in __init__
    raise RuntimeError("Server refused upload: %s" % msg.msg)
RuntimeError: Server refused upload: Failed to create upload
`

The server log shows this traceback:

`Sep 28 14:59:29 ssfAntergos dync-server[25058]: ERROR:dync.server:Exception while creating new upload.
Sep 28 14:59:29 ssfAntergos dync-server[25058]: Traceback (most recent call last):
Sep 28 14:59:29 ssfAntergos dync-server[25058]:   File "/home/sven1103/git/dync/dync/server.py", line 229, in serve
Sep 28 14:59:29 ssfAntergos dync-server[25058]:     self._add_upload(msg)
Sep 28 14:59:29 ssfAntergos dync-server[25058]:   File "/home/sven1103/git/dync/dync/server.py", line 146, in _add_upload
Sep 28 14:59:29 ssfAntergos dync-server[25058]:     file = self._storage.add_file(msg.name, msg.meta, msg.origin)
Sep 28 14:59:29 ssfAntergos dync-server[25058]:   File "/home/sven1103/git/dync/dync/storage.py", line 37, in add_file
Sep 28 14:59:29 ssfAntergos dync-server[25058]:     assert not os.path.exists(destination)
Sep 28 14:59:29 ssfAntergos dync-server[25058]: AssertionError
`

Would be cool to give the user some more informative message, such as: File already exists. Something like that

**Comment by aseyboldt** [comment]
A part of this is already done in 6d8d4aa50028d11da567fc008eaea70d025a85f7. But the code in `storage.py` does not produce nice exception messages and the client should probably be smart enough not to print a traceback, but a nicely formatted version of the error from the server.

**Comment by sven1103** [comment]
This commit was done on your master branch, not on the fork on qbicsoftware. Any idea how to merge that into qbisoftware master?

**Comment by aseyboldt** [comment]
Done in #2

**Comment by aseyboldt** [comment]
Now that we have an `InvalidUploadException` we should catch that in `add_upload` and send a 4xx error code. The client should check if the error code is `400 <= code < 500` and  if so print a nice message containing the error message from the server (without traceback).
